### ISSUE TITLE
CompanyHero: Text sizes

### ISSUE THREAD

**Issue by ipeglin** [et-dagen/et-dagen#115]
**Describe the bug**
Text sizes for the CompanyHero component are larger than the main landing header. These should preferably be smaller.

**Screenshots**
![image](https://github.com/et-dagen/et-dagen/assets/26115581/2f8fdbe0-8e23-4f0f-9ff0-c75177472728)

**Comment by JStoresund** [comment]
I agree. However, according to the figma design, the main title (in the homebanner component) doesn't look like it's supposed to be bold. Disregarding this, if the 'hovedpartner' text becomes smaller than H4, it looks odd.
Upon doing some testing, I think the best way to go would be to increase the size of the homebanner header, and also reduce the size of the companyhero header (I agree it's a bit of a monster). I'll add a draft of how it looks when just reducing the companyhero header. It takes a bit more work to change the size of the homebanner header, so I'll leave that out for now. I also downsized the company title, since it definitely shouldn't be the same size as the header.
